# Generated by Django 4.0.3 on 2022-05-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=30, verbose_name='Название рейса')),
                ('departure_time', models.DateTimeField(verbose_name='Дата и время вылета')),
                ('route_info', models.TextField(verbose_name='Информация о рейсе')),
                ('arrival_time', models.DateTimeField(verbose_name='Дата и время рейса прилёта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['route'],
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('user_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('user_patronymic', models.CharField(max_length=25, verbose_name='Отчество')),
                ('user_mail', models.EmailField(max_length=50, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['user_surname'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_time_buy', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.myuser')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
